### PR TITLE
Install Afterpay module with Composer

### PR DESCRIPTION
**Pull request by dverkade**
**Description**

The current module is not installable with Composer due to the folder structure being used. Using Composer to install 3rd party modules is best practice for Magento 2, so that they can easily be updated to the latest release. 

**What has been done**

- Changed the folder structure of the module so that it's installable with Composer.
- Changed the README.md file so that it uses actual markup language instead of HTML. 

**Composer installation**

Module is now installable with composer:

-  Add the GIT repo as a repository in your composer.json file (Ideally add this module to packagist.org, so that this step can be skipped in the future)
```
    "repositories": [
        {
            "type": "git",
            "url": "git@github.com:afterpay/afterpay-magento-2.git"
        }
```
- Install with composer:
```
composer require afterpay/module-afterpay
```

**Manual installation**

- Download the ZIP version of the repository
- Create directory app/code/Afterpay/Afterpay
- Copy content of the ZIP file into the newly created directory.

### CODE REVIEW

**Comment by nntoan** [comment]
@benfterpay Hi Ben, can we have this merged? Copying directory into app/code is so annoying.

Thanks :)

**Comment by DerringersMusic** [comment]
Hi @benfterpay , 

Using composer is best practice and should be the default method. Please review @dverkade's work and commit this to the branch if it meets expectations.

**Comment by kaushikrohit54** [comment]
[InvalidArgumentException]                                                                                                                                            
  Could not find a matching version of package afterpay/module-afterpay. Check the package spelling, your version constraint and that the package is available in a st  
  ability which matches your minimum-stability (stable).

**Comment by magent-harsh** [comment]
dsd

**Comment by afterpayplugins** [comment]
Thank you for your valuable contribution.
Closing the PR as the issue has been already addressed.

**Pull request closed without merging**
